global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'service-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8500'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8600'] ## only for demo purposes don't use host.docker.internal in production
